import type { OutcomeDefinition } from './probability-calibration';
/** Stable identity for persisted decisions. New intraday thresholds are unvalidated baselines. */
export const STRATEGY_IDS = ['bpjs', 'bsjp', 'swing', 'ara'] as const;
export type StrategyId = typeof STRATEGY_IDS[number];
export type StrategySupportLevel = 'ready' | 'partial' | 'unavailable';
export interface StrategyIdentity { strategy_id: StrategyId; strategy_version: string; configuration_version: string; execution_model: string; outcome_definition: OutcomeDefinition }
export interface StrategyWindow { start: string; end: string; sessionOffset: number }
export interface StrategyProfile {
  id: StrategyId; name: string; description: string; horizon: string; version: string; configurationVersion: string;
  timezone: 'Asia/Jakarta'; screening: StrategyWindow; entry: StrategyWindow; exit: StrategyWindow;
  dataRequirements: readonly string[]; freshness: { intradaySeconds: number; orderbookSeconds: number; newsHours: number };
  eligibilityRules: readonly string[]; rankingFactors: readonly string[];
  risk: { maxSpreadPercent: number; minimumTradedValueIdr: number; minimumSameClockRelativeVolume: number; stopPercent: number | null; targetPercent: number | null; maxRiskPercent: number; maxParticipationPercent: number; overnight: boolean };
  executionModel: string; outcomeDefinition: OutcomeDefinition;
  backtest: { resolution: 'daily' | 'intraday'; holdingSessions: readonly number[]; eventOnly: boolean; sameBarPolicy: 'mark_ambiguous'; requireHistoricalUniverse: true; requireTemporalHoldout: true };
  baselineStatus: 'existing_baseline' | 'unvalidated_baseline';
}
const common = { timezone: 'Asia/Jakarta' as const, freshness: { intradaySeconds: 300, orderbookSeconds: 60, newsHours: 24 }, risk: { maxSpreadPercent: 1, minimumTradedValueIdr: 1_000_000_000, minimumSameClockRelativeVolume: 1.2, stopPercent: 1.5, targetPercent: 3, maxRiskPercent: 1, maxParticipationPercent: 1, overnight: false }, backtest: { resolution: 'intraday' as const, holdingSessions: [1], eventOnly: false, sameBarPolicy: 'mark_ambiguous' as const, requireHistoricalUniverse: true as const, requireTemporalHoldout: true as const }, baselineStatus: 'unvalidated_baseline' as const };
const window = (start: string, end: string, sessionOffset = 0): StrategyWindow => ({ start, end, sessionOffset });
export const STRATEGIES: Readonly<Record<StrategyId, StrategyProfile>> = Object.freeze({
  bpjs: { ...common, id: 'bpjs', name: 'BPJS', description: 'Beli Pagi Jual Sore: sinyal pagi, exit paling lambat sore pada sesi bursa yang sama.', horizon: 'Intraday · sesi yang sama', version: 'bpjs-v1', configurationVersion: 'bpjs-baseline-v1', screening: window('09:15', '10:30'), entry: window('09:15', '10:30'), exit: window('15:30', '15:45'), dataRequirements: ['completed_intraday_candles', 'same_clock_volume_history', 'timestamped_orderbook', 'verified_exchange_calendar'], eligibilityRules: ['verified_continuous_session', 'morning_entry_window', 'fresh_completed_intraday', 'positive_momentum', 'above_vwap', 'same_clock_rvol', 'spread_and_liquidity'], rankingFactors: ['opening_momentum', 'opening_range_breakout', 'price_vs_vwap', 'same_clock_rvol', 'spread', 'liquidity'], executionModel: 'intraday_next_bar_open_v1', outcomeDefinition: 'bpjs_same_session_net_return_positive' },
  bsjp: { ...common, id: 'bsjp', name: 'BSJP', description: 'Beli Sore Jual Pagi: entry sore dan exit pagi pada sesi bursa berikutnya, dengan risiko gap.', horizon: 'Sore → pagi sesi bursa berikutnya', version: 'bsjp-v1', configurationVersion: 'bsjp-baseline-v1', screening: window('15:00', '15:30'), entry: window('15:00', '15:30'), exit: window('09:00', '09:30', 1), dataRequirements: ['completed_intraday_candles', 'same_clock_volume_history', 'timestamped_orderbook', 'verified_exchange_calendar', 'next_trading_session'], eligibilityRules: ['verified_continuous_session', 'afternoon_entry_window', 'fresh_completed_intraday', 'positive_momentum', 'above_vwap', 'same_clock_rvol', 'spread_and_liquidity', 'next_session_verified'], rankingFactors: ['afternoon_momentum', 'session_range_position', 'price_vs_vwap', 'same_clock_rvol', 'liquidity'], risk: { ...common.risk, overnight: true }, executionModel: 'overnight_next_bar_open_v1', outcomeDefinition: 'bsjp_next_session_morning_net_return_positive' },
  swing: { ...common, id: 'swing', name: 'SWING', description: 'Baseline momentum, relative strength dan broker persistence dengan horizon 5–20 sesi.', horizon: '5–20 sesi bursa', version: 'swing-5-20d-v1', configurationVersion: 'eligibility-execution-v2', screening: window('09:00', '16:15'), entry: window('09:00', '15:45'), exit: window('09:00', '15:45', 20), dataRequirements: ['completed_daily_ohlcv', 'broker_summary', 'benchmark', 'timestamped_orderbook'], eligibilityRules: ['existing_swing_eligibility_v2'], rankingFactors: ['momentum', 'relative_strength', 'broker_persistence', 'execution', 'market_regime'], freshness: { ...common.freshness, newsHours: 120 }, risk: { ...common.risk, maxSpreadPercent: 3, stopPercent: null, targetPercent: null, overnight: true }, executionModel: 'entry_zone_conservative', outcomeDefinition: 'net_return_10d_positive', backtest: { ...common.backtest, resolution: 'daily', holdingSessions: [5, 10, 20] }, baselineStatus: 'existing_baseline' },
  ara: { ...common, id: 'ara', name: 'ARA', description: 'Kandidat berpotensi menyentuh batas ARA resmi setelah cutoff pada sisa sesi; monitoring dipisahkan dari eksekusi.', horizon: 'Cutoff → akhir sesi yang sama', version: 'ara-v1', configurationVersion: 'ara-baseline-v1', screening: window('09:15', '15:30'), entry: window('09:15', '15:30'), exit: window('15:50', '16:15'), dataRequirements: ['completed_intraday_candles', 'same_clock_volume_history', 'timestamped_orderbook', 'official_ara_limit', 'verified_exchange_calendar'], eligibilityRules: ['verified_continuous_session', 'official_session_ara', 'not_touched_before_cutoff', 'fresh_completed_intraday', 'two_sided_execution_book', 'positive_momentum', 'same_clock_rvol'], rankingFactors: ['distance_to_official_ara', 'intraday_momentum', 'same_clock_rvol', 'liquidity'], risk: { ...common.risk, stopPercent: null, targetPercent: null }, executionModel: 'ara_event_only_no_assumed_fill_v1', outcomeDefinition: 'official_ara_touched_after_cutoff', backtest: { ...common.backtest, eventOnly: true } },
});
export function isStrategyId(value: unknown): value is StrategyId { return typeof value === 'string' && STRATEGY_IDS.includes(value as StrategyId); }
export function parseStrategyId(value: unknown, fallback: StrategyId = 'swing'): StrategyId { if (value === undefined || value === null || value === '') return fallback; if (!isStrategyId(value)) throw new RangeError('Strategy ID tidak valid; gunakan bpjs, bsjp, swing, atau ara.'); return value; }
export function getStrategy(id: StrategyId): StrategyProfile { return STRATEGIES[id]; }
export const getStrategyProfile = getStrategy;
export function strategyIdentity(id: StrategyId): StrategyIdentity { const p = getStrategy(id); return { strategy_id: id, strategy_version: p.version, configuration_version: p.configurationVersion, execution_model: p.executionModel, outcome_definition: p.outcomeDefinition }; }
export function strategyPartitionKey(identity: StrategyIdentity, runId: string, cutoffAt: string) { return [identity.strategy_id, identity.strategy_version, identity.configuration_version, identity.execution_model, identity.outcome_definition, runId, cutoffAt].join('|'); }
export function providerStrategySupport(id: StrategyId): { level: StrategySupportLevel; reasons: string[] } {
  return id === 'swing' ? { level: 'partial', reasons: ['Daily OHLCV dan baseline tersedia; kesiapan eksekusi bergantung freshness provider dan arsip point-in-time.'] } : { level: 'unavailable', reasons: ['Adapter provider belum menyediakan arsip candle intraday selesai dan volume pembanding pada jam yang sama.', 'Kalender sesi bursa dan provenance timestamp orderbook harus diverifikasi sebelum entry.', ...(id === 'ara' ? ['Batas ARA resmi per simbol/sesi dengan timestamp sumber belum tersedia.'] : [])] };
}
